### PR TITLE
Add option to disable Hangfire

### PR DESCRIPTION
**Pull request by stevetemple**
Just thinking about an option to disable on certain environments, for example local dev, or front end servers in a load balanced environment

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Nice one @stevetemple !! I'm on holiday for a few weeks but will have a look when I'm back.

**Comment by nul800sebastiaan** [comment]
Just did a quick test for my Job Scheduler and it looks like this:

```csharp
public class JobsComposer : IComposer
{
    private static string GetTiming(string timing, bool disabled)
    {
        return disabled ? Cron.Never() : timing;
    }
    
    public class HangfireSettings
    {   
        public bool? Disabled { get; set; }
    }

    public void Compose(IUmbracoBuilder builder)
    {
        var settings = builder.Config.GetSection("Hangfire").Get<HangfireSettings>();
        var hangfireDisabled = settings.Disabled.GetValueOrDefault(false);

        RecurringJob.AddOrUpdate<ITestService>($"This is a test job", x =>
            x.RunTestJob(null), GetTiming(Cron.Daily(), hangfireDisabled));
    }
}
```

The most important part is the `GetTiming(Cron.Daily(), hangfireDisabled)` call when scheduling the job - if Hangfire is disabled in the `appSettings.json` which looks like so:

image


If Hangfire is disabled, jobs are still scheduled but will never run, but can be ran manually.

To not schedule any jobs, you could write it differently like this and then `GetTiming` is not needed.

```csharp
public void Compose(IUmbracoBuilder builder)
{
    var settings = builder.Config.GetSection("Hangfire").Get<HangfireSettings>();
    var hangfireDisabled = settings.Disabled.GetValueOrDefault(false);

    if (!hangfireDisabled)
    {
        RecurringJob.AddOrUpdate<ITestService>($"This is a test job", x =>
            x.RunTestJob(null), Cron.Daily());
    }
}
```

**Comment by stevetemple** [comment]
I thought you were on holiday 🤨 

I'd just tweaked it, realised that it wouldn't let jobs be added, just want the server side of it turned off but all servers could schedule jobs just won't run them.

Meant to open this as a draft as I was just pitching the idea

**Comment by stevetemple** [comment]
Running this on a production website, where the front end servers are disabled, but backoffice server enabled, works well

I would probably change the setting name to Hangfire:Server:Disabled as it's the server part that is disabled rather than anything else. The front end servers can still add tasks etc but they'll only be run on the backoffice server

**Comment by nul800sebastiaan** [comment]
Sorry for the delay @stevetemple 
I couldn't contrib back to your branch, but I took your suggestion and made it into:

```json
  "Hangfire": {
    "Server": {
      "Disabled": true
    }
  }
```

image

Additionally, you were hiding the dashboard on instances that were not a server, which turned into an infinite spinner, I think it's fine to show the dashboard even if the current machine is not a server.

Merged in https://github.com/nul800sebastiaan/Cultiv.Hangfire/commit/622d88f2ee5ced4f35ccaf6e621afd0f2a8f9144 and will be released in v3.1.0 in a few minutes.

**Pull request closed without merging**
